### ISSUE TITLE
Tokenization is ignored when importing xml file with multiple objects included

### ISSUE THREAD

**Issue by stsang** [lispercat/sailpoint-iiq-dev-accelerator#10]
If you import an xml object that uses the <sailpoint> tag to include multiple objects, the variable tokenization is not performed.

Add to your x.target.properties:
%%ROLEA%%=ROLEA
%%ROLEB%%=ROLEB

```
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE sailpoint PUBLIC "sailpoint.dtd" "sailpoint.dtd">
<sailpoint>
    <Bundle displayName="Role A" name="Role A" type="it">
        <Profiles>
            <Profile>
                <ApplicationRef>
                    <Reference class="sailpoint.object.Application" name="Active Directory"/>
                </ApplicationRef>
                <Constraints>
                    <Filter operation="CONTAINS_ALL" property="memberOf">
                        <Value>
                            <List>
                                <String>%%ROLEA%%</String>
                            </List>
                        </Value>
                    </Filter>
                </Constraints>
            </Profile>
        </Profiles>
    </Bundle>

    <Bundle displayName="Role B" name="Role B" type="it">
        <Profiles>
            <Profile>
                <ApplicationRef>
                    <Reference class="sailpoint.object.Application" name="Active Directory"/>
                </ApplicationRef>
                <Constraints>
                    <Filter operation="CONTAINS_ALL" property="memberOf">
                        <Value>
                            <List>
                                <String>%%ROLEB%%</String>
                            </List>
                        </Value>
                    </Filter>
                </Constraints>
            </Profile>
        </Profiles>
    </Bundle>
</sailpoint>
```

**Comment by lispercat** [comment]
I tried your example
For me %%ROLEB%% gets correctly tokenized to  ROLEB.
If I put  %%ROLEA%% it gets tokenized to an empty string since it's
overridden to an empty string.
Let me know if I am missing something

**Comment by lispercat** [comment]
Is it possible that you get errors during importing your Bundle object?
In your example you didn't specify the header for DOCTYPE.
Try following:
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE Bundle PUBLIC "sailpoint.dtd" "sailpoint.dtd">
<Bundle displayName="Role B" name="Role B" type="it">
    <Profiles>
        <Profile>
            <ApplicationRef>
                <Reference class="sailpoint.object.Application" name=
"Active Directory"/>
            </ApplicationRef>
            <Constraints>
                <Filter operation="CONTAINS_ALL" property="memberOf">
                    <Value>
                        <List>
                            <String>%%ROLEB%%</String>
                        </List>
                    </Value>
                </Filter>
            </Constraints>
        </Profile>
    </Profiles>
</Bundle>

**Comment by stsang** [comment]
Can you take a look at my modified post? I edited the post to put it in a codeblock.

The DOCTYPE needs to be sailpoint instead of Bundle when you are trying to import multiple objects. Notice that I have two bundle objects defined within the <sailpoint> </sailpoint> tags.

**Comment by lispercat** [comment]
ok, please ignore my previous messages, I read my email and it didn't show your full message.
if I put following in the *.target.properties:
%%ROLEA%%=ROLEA
%%ROLEB%%=ROLEB

Both ROLEA and ROLEB in your example get correctly tokenized.
Do I miss something?

**Comment by lispercat** [comment]
yep, tried it again, it perfectly tokenized both roles

**Comment by lispercat** [comment]
Yes, that's exactly what I did. It works well for me

**Comment by stsang** [comment]
That's strange, you're right. It's importing in correctly now. I tried it a few times between Eclipse and VSCode, getting different results. Sorry to waste your time.

**Comment by lispercat** [comment]
no worries!
