### ISSUE TITLE
Ability to modify iiqCustom.properties files through vscode

### ISSUE THREAD

**Issue by nbhansali** [lispercat/sailpoint-iiq-dev-accelerator#14]
Would it be possible to update iiqCustom.properties files for custom text through the plugin?

**Comment by lispercat** [comment]
Could you give an example of what you are trying to do?

**Comment by nbhansali** [comment]
I'm customizing the OOTB self-registration page & want to update the properties file through the plugin.

**Comment by lispercat** [comment]
I am not sure I understand what you mean by "want to update the properties
file through the plugin".
Can you list the actions that you are currently doing manually?

**Comment by nbhansali** [comment]
Nevermind, I was trying to do something that wasn't needed!
