### ISSUE TITLE
Check the SSB's x.secret.properties in addition to target.properties for ECLIPSE_ tokens

### ISSUE THREAD

**Issue by drosenbauer** [lispercat/sailpoint-iiq-dev-accelerator#16]
This will reduce the risk of accidentally committing critical passwords into source control.

**Comment by lispercat** [comment]
I found a reference to ${target}.target.secret.properties in
scripts/build.config.xml (wonder why they duplicate "target" in the file
name. ${target}.secret.properties would be enough)
Is that what you are referring to?
Thanks, I will keep that in mind as a feature request.

**Comment by lispercat** [comment]
Devin, I added the feature that you requested. Please verify that it works
for you.

**Comment by lispercat** [comment]
Implemented and closed
