### ISSUE TITLE
Like to see these features

### ISSUE THREAD

**Issue by nbhansali** [lispercat/sailpoint-iiq-dev-accelerator#2]
- The right-click import on the file doesn't actually import anything.
- Would like the ability to import multiple files at once as I can do in the eclipse plugin.

**Comment by lispercat** [comment]
Thanks! I'll take a look at the right-click issue.
I am currently working on a "full deployment" feature so after that I'll have a look at multiple file import.
Question is where would you select them? As an easy solution we can import all currently open files in VSCode

**Comment by lispercat** [comment]
I fixed the right-click command issue.
Also I added a new feature as "full deployment", please check it out
Let me know how you would like to select files for "partial deployment", is it ok to deploy all opened xml files in the VSCode?

**Comment by nbhansali** [comment]
Awesome thanks! I'll check out the "full deployment" feature. Would it be possible to multi-select all the ones you want to deploy in the project explorer?

**Comment by lispercat** [comment]
I found some bug in my full deployment. Working on the fix now.
I think selecting files is the VSCode explorer could be a bit awkward,
since the files are in different folders all over the project. To me the
most viable solution seems to be opening all those files in vscode so for
me, the open XML file would indicate you want to deploy it.

**Comment by nbhansali** [comment]
That's dangerous because you might have files open you're unaware of.

**Comment by lispercat** [comment]
So true!

**Comment by lispercat** [comment]
But then again, I always give the last chance to cancel the deployment by
showing the list of files

**Comment by lispercat** [comment]
OK, I pushed a fix for custom deployment in 1.0.7
The command is "Deploy Custom Build"

**Comment by nbhansali** [comment]
Would it be possible to do a comparison between your local file and what is deployed on the server?

**Comment by lispercat** [comment]
@nbhansali As something that already exists, you can execute iiq command "Get Object" and then  "Compare Active File with Saved".

**Comment by lispercat** [comment]
@nbhansali I pushed the new feature "Compare Local with Deployed" in the 1.0.14. Please check it out

**Comment by nbhansali** [comment]
Appreciate it!! Thanks for all the quick fixes - the tool is very useful.

**Comment by nbhansali** [comment]
@lispercat would it be possible to implement a linter/formatter for sailpoint's beanshell code?

**Comment by lispercat** [comment]
For that I'd need to implement a language server (or/and reuse the existing
Java language server extension).
I am keeping an eye on that, but it's a big undertaking.
Some day, I hope so
