### ISSUE TITLE
Switch Environment

### ISSUE THREAD

**Issue by labbynary** [lispercat/sailpoint-iiq-dev-accelerator#25]
I'm not been able to add more than one environment. How can I do it?

**Comment by lispercat** [comment]
The environment is defined by a <env-name>.target.properties file under
your root folder (the folder that has build.bat, build.properties etc).
You can create a new environment by copying your existing environment files
into <new-env>.target.properties, <new-env>.iiq.properties,
<new-env>.log4j2.properties etc.
Then the extension will offer it in the list of available environments when
you want to switch.

**Comment by lispercat** [comment]
Answered the question
