### ISSUE TITLE
Beanshell operators causing error in VS Code

### ISSUE THREAD

**Issue by RubyUdders** [lispercat/sailpoint-iiq-dev-accelerator#34]
Not sure if this is related to the plugin but using the @and, @or etc. Beanshell operators in rules, forms and workflows causes syntax highlighting errors in vscode.

Is there any way to fix these errors? I am not sure if it's the plugin, the XML syntax highlighting or something else that causes the syntax errors.

**Comment by lispercat** [comment]
Hmm, never saw this before, but if you can reproduce it, you can always try to play with https://github.com/lispercat/sailpoint-iiq-dev-accelerator/blob/master/syntaxes/beanshell-injection.json and propose a PR
