### ISSUE TITLE
Security Concern with Credetials.

### ISSUE THREAD

**Issue by parithon** [lispercat/sailpoint-iiq-dev-accelerator#35]
I work for an organization which has a security concern with saving credentials using either the vscode settings.json file or the *.target.properties files as they would be saved in clear text on the users' disk. Instead, it would be great if we could utilize vscode's account provider which would save the credentials within the users' keystore.

**Comment by lispercat** [comment]
Interesting feature, I don't have time for it now, but you are welcome to contribute to the project!
