### ISSUE TITLE
Unable to deploy uncommitted changes

### ISSUE THREAD

**Issue by stsang** [lispercat/sailpoint-iiq-dev-accelerator#38]
Hi! When using command palette to deploy uncommitted changes, this error occurs.

![image](https://user-images.githubusercontent.com/3847921/208173442-2563aaa0-d1ba-4f6c-b870-6f60287b78d3.png)

**Comment by lispercat** [comment]
Yep, it's the issue of VSCode version 1.74.1. The plugin code didn't change.

**Comment by lispercat** [comment]
Fixed in 1.0.41

**Comment by lispercat** [comment]
Fixed in 1.0.41
