### ISSUE TITLE
Import doesn't check/prompt for any missing properties

### ISSUE THREAD

**Issue by nbhansali** [lispercat/sailpoint-iiq-dev-accelerator#4]
Hey! It seems like the import current file doesn't check for any missing property that exists in the file. Any way we can prompt the user that there is a missing property with the name of the property if a property does not align in the file?

**Comment by lispercat** [comment]
can you give an example?

**Comment by nbhansali** [comment]
For example I have a workflow object calling out to a variable set in my properties file %%AD_HOST%% and the value is missing in my properties file the import will suceed but my workflow will fail.

**Comment by lispercat** [comment]
got it, I'll see what I can do

**Comment by lispercat** [comment]
@nbhansali I've done the fix, please check it out in 1.0.15

**Comment by nbhansali** [comment]
Awesome - thanks!
