### ISSUE TITLE
It should be possible to import several files or files in a folder

### ISSUE THREAD

**Issue by yannick-beot-sp** [lispercat/sailpoint-iiq-dev-accelerator#40]
At this moment, it is only possible to important 1 file from the file explorer.
A "Solution" can be composed of several objects and thus, several XML files. 
These files can be in a single folder.

To ease the deployments of "artifacts", it should be possible to import several files.

**Comment by lispercat** [comment]
There are a few ways to import files:
1) Import one current file
2) Import all uncommitted changes
3) Import all open files in the workspace
4) Build and import the whole SSB set

**Comment by lispercat** [comment]
Ctrl-Shift-p and type "iiq deploy open files"

**Comment by lispercat** [comment]
Merged
