### ISSUE TITLE
Default folder when getting objects

### ISSUE THREAD

**Issue by yannick-beot-sp** [lispercat/sailpoint-iiq-dev-accelerator#41]
When using the "get object" command, a file with a random identifier is created in the temp folder.
It often results on the same steps:
1. Copy path of the target folder
2. Go to file "temp" file and save as
3. Paste the folder
4. Remove the random id for clean file name

It should be possible to define folders within the workspace.

An idea is to have an additional settings for a pattern. For instance:
```
%x/%e/%o/%o-%n-%y%M%d-%h%m%s.xml
```
Where:
- `%x` : workspace folder
- `%e`: name of the environment (as the one display in the status bar)
- `%o`: name of the object type (Rule, Form, etc.)
- `%n`: name of the object
- `%y`,  `%M`, `%d`, etc.: parts of the date

**Comment by lispercat** [comment]
Please take a look at "Export Object" session at
https://marketplace.visualstudio.com/items?itemName=AndreiStebakov.sailpoint-iiq-dev-accelerator

It should get all objects in one folder, see if it works for you.
For your scenario it would probably be easier to just copy the content of
the object that you got and paste it in any target file with the name that
you need.

**Comment by yannick-beot-sp** [comment]
This is only available for all objects of the chosen object types

**Comment by lispercat** [comment]
You can check the top check button which will select all object types so
you'll get them all.

**Comment by lispercat** [comment]
Merged
