### ISSUE TITLE
Sort options

### ISSUE THREAD

**Issue by yannick-beot-sp** [lispercat/sailpoint-iiq-dev-accelerator#44]
At this moment, objects are sorted by names in the dropdowns.
It should be possible to sort by "last modified" date to get last modified objects more quickly.

**Comment by lispercat** [comment]
Sure, there are many ways to do it. On the other hand, it's so easy to get
the right name by starting to type in the search, so not sure if the effort
makes sense.
Some may prefer sorting by name. But in any case you are always welcome to
propose a PR.

**Comment by yannick-beot-sp** [comment]
I agree it is super easy to find the object.
It is more a question of visualisation.

**Comment by lispercat** [comment]
Merged
