### ISSUE TITLE
Refresh object command is not refreshing the object

### ISSUE THREAD

**Issue by yannick-beot-sp** [lispercat/sailpoint-iiq-dev-accelerator#45]
The "refresh object" command will either:
- Diff between the current file and the object in the server
- Open the object in a temp file

When I want to refresh the object, I would like the server version of the object that has been updated outside VSCode.

This "refresh object" should be split in 3 commands:
- "Diff" with server version
- "Open the current object" that would open the object in a temp file
- "Refresh" that would actually update the content of the current file

Otherwise, you have to:
1. Execute the "Refresh the object" command
2. Should to not diff
3. Copy the content of the temp file
4. Paste to the current file

**Comment by lispercat** [comment]
Yeah, I to me the "refresh object" is basically the same a "get object" with an option to display the diff. 
So like you mentioned, your scenario would be covered by doing some extra copy/paste step.
I rarely use the scenario (if ever) so if I do need it, I don't mind doing that extra step.
If you use it a lot, it would probably make sense for you to include that extra option (maybe disabled by default but available with options) so yeah, feel free to create a PR.
