### ISSUE TITLE
&amp;&amp; is replaced in attribute value

### ISSUE THREAD

**Issue by yannick-beot-sp** [lispercat/sailpoint-iiq-dev-accelerator#50]
The extension is "naively" replacing all `&amp;&amp;` by `&&`.
For workflows, && can be used for conditions. However, they must not be replaced in order to be a valid XML.

**Comment by lispercat** [comment]
I agree, there are cases where it shouldn't be done. I need to make it
smarter so that it would only replace them within CDATA tags

**Comment by lispercat** [comment]
Awesome, thanks!

**Comment by lispercat** [comment]
We merged the PR, can close the ticket now
