### ISSUE TITLE
Boolean value can't be imported using plugin

### ISSUE THREAD

**Issue by nbhansali** [lispercat/sailpoint-iiq-dev-accelerator#6]
Hey! Looks like we can't import files that store boolean value paramters. For instance, an application object with AD configurations & flipping the TLS value back & forth fails import from VS code.

<img width="490" alt="Screen Shot 2020-10-19 at 10 12 29 PM" src="https://user-images.githubusercontent.com/2665470/96531848-8d2eab00-1258-11eb-88f9-bb605f3b97bd.png">

**Comment by lispercat** [comment]
thanks, I'll take a look

**Comment by lispercat** [comment]
@nbhansali I fixed it in 1.0.17, please verify

**Comment by nbhansali** [comment]
Thanks!!!
