### ISSUE TITLE
Escape character in tokenization

### ISSUE THREAD

**Issue by stsang** [lispercat/sailpoint-iiq-dev-accelerator#8]
Could you take this into consideration? When tokenizing variables, the \ char is not recognized as an escape character, e.g. when there are two \\ it should be replaced to a single \

%%FTP_PATH%%=C:\\\Temp\\\Files

This is causing backwards compatibility with the Eclipse plugin.

**Comment by lispercat** [comment]
Let me confirm this:
In your config file the line actually goes:
%%FTP_PATH%%=C:\\Temp\\Files
Correct?

**Comment by stsang** [comment]
Yes, that's what I meant. For some reason github escaped the double char in my post.

**Comment by lispercat** [comment]
@stsang I made a fix in 1.0.19. Please check

**Comment by stsang** [comment]
Verified, thanks!
