### ISSUE TITLE
Typo in result

### ISSUE THREAD

**Issue by nbhansali** [lispercat/sailpoint-iiq-dev-accelerator#9]
Minor issue but there's a typo when outputting the result of a rule.

![Screen Shot 2020-11-09 at 11 49 55 AM](https://user-images.githubusercontent.com/2665470/98570681-b18f0d80-2281-11eb-8119-07c9a15ad5f6.png)

**Comment by lispercat** [comment]
Good catch, thanks!

**Comment by lispercat** [comment]
@nbhansali fixed in 1.0.20, thanks!

**Comment by lispercat** [comment]
fixed in 1.0.20,
